### ISSUE TITLE
Salvando o momento atual do projeto

### ISSUE THREAD

**Issue by santiago-nath** [cassiobotaro/do_zero_a_implantacao#35]
Descrever que o aluno deve salvar o txt, ficou confuso este trecho. =)

**Comment by nilold** [comment]
Olá @santiago-nath , de qual trecho exatamente você está falando?

**Comment by santiago-nath** [comment]
Este trecho:
" Para evitar este problema definiremos arquivos com as dependências que instalamos no nosso projeto."

Mesmo colocando a extensão do arquivo, acho que ficamos confusos que nós devíamos criar o .txt

**Comment by cassiobotaro** [comment]
Achei válido o apontamento e acho que podemos melhorar no texto.
