### ISSUE TITLE
Iniciando o projeto

### ISSUE THREAD

**Issue by alermartins** [cassiobotaro/do_zero_a_implantacao#36]
- [x] Em "Começando a tirar do papel o projeto", na imagem evidenciar o que deve estar marcado. 

- [x] Nos comandos, informar que o link deve ser retirado do github do usuário. 

- [x] Todos os comandos para Windows estão com python**3**, enquanto deveria ser **python** apenas. 

- [x] Evidenciar onde se deve criar pastas e arquivos.

**Comment by alermartins** [comment]
O comando from gerenciador_tarefas.gerenciador import app, TAREFAS não está explicado

**Comment by cassiobotaro** [comment]
@alermartins achei todos os prolemas apontados válidos e transformei-os em uma lista de tarefas a serem feitas.
