### ISSUE TITLE
"Mandando o foguete para o espaco" é necessário criar o runtime.txt informando o python

### ISSUE THREAD

**Issue by kylefelipe** [cassiobotaro/do_zero_a_implantacao#45]
É necessário criar no root do projeto um arquivo runtime.txt com python-3.8.0, pois sem isso o heroku cria o repositorio com o python 3.6, que é o padrão dele.

Lembre de adicionar ele no git add

**Comment by cassiobotaro** [comment]
Decidi não adicionar este arquivo, pois é uma complexidade a mais. Dado que o projeto é feito pensado para rodar em versões 3.6+, não tem problema a versão padrão ser 3.6 em produção, mas acho que cabe um alerta.

**Comment by cassiobotaro** [comment]
a2c054d1d894d1243117e49de1d22168874f64b9
