### ISSUE TITLE
Problemas no Heroku  depois de subir a aplicação

### ISSUE THREAD

**Issue by kylefelipe** [cassiobotaro/do_zero_a_implantacao#47]
Ao tentar subir a aplicação no heroku estou recbendo o sequinte erro ao acessar ele 
```Shell
heroku[router]: at=error code=H14 desc="No web processes running" method=GET path="/" host=shrouded-sands-67690.herokuapp.com request_id=4d6076f6-ac15-41eb-9382-7181cf566c0b fwd="187.86.245.112" dyno= connect= service= status=503 bytes= protocol=https
```

**Comment by cassiobotaro** [comment]
Possíveis causas:

- Erro no seu arquivo Procfile
- Arquivo Procfile não foi enviado a heroku

**Comment by cassiobotaro** [comment]
O tutorial foi testado no dia 26/12/2019 e não apresentou problema, então acredito que seja algum problema com o Procfile. Caso o problema persista, reabra a issue.
