### ISSUE TITLE
Adicionar novas referências

### ISSUE THREAD

**Issue by cassiobotaro** [cassiobotaro/do_zero_a_implantacao#53]
Algumas sugestões: 
- live de python
- livro Pense em python
- documentações de frameworks utlizados

**Comment by ekkopy** [comment]
Algumas sugestões para estudos iniciantes e intermediários de Python :snake: 

### Ta afim de conhecer mais sobre Django  e/ou Flask ?! Então se ligas nessas feras:

    - Regis do Python [PT-BR]: https://www.youtube.com/channel/UCSCeh6nJILegqsqsS1WizOQ
    - Bruno Rocha (CodeShow) [PT-BR]: https://www.youtube.com/user/brunovegan
    - Eduardo Mendes (Live de Python) [PT-BR]: https://www.youtube.com/user/mendesesduardo
    
### Procura algo como utilização de Python em AI ? Neural Network ? Então você procura pelo SentDex!

     - Sentdex [EN-US]: https://www.youtube.com/user/sentdex/videos

### Sempre procure pela documentação:

    - Django: https://docs.djangoproject.com/en/3.0/
    - Flask: http://flask.palletsprojects.com/en/1.1.x/

### Participe das comunidades! Seja ativo(a)!

   - Python MG: https://t.me/pythonmg
   - Live de Python: https://t.me/livepython

### Livros úteis e cursos 0800: 
   
## Tá afim de conhecer como o python funciona e de quebra aprender como utilizar a linguagem em Pentest ?! Então se liga no canal do caveira :skull: 
      
  - Caveira Tech: https://www.youtube.com/playlistlist=PLp95aw034Wn_WtEmlepaDrw8FU8R5azcm  
 - Guanabara:https://www.youtube.com/watchv=0LB3FSfjvao&list=PLHz_AreHm4dksnH2jVTIVNviIMBVYyFnH
   
## Alguns livros disponibilizados de maneira gratuita mas em inglês: 
    
    - Livros: http://www.allitebooks.org/

**Comment by cassiobotaro** [comment]
As novas referências foram adicionadas!
