### ISSUE TITLE
Erro de importação

### ISSUE THREAD

**Issue by AugustoBaden** [cassiobotaro/do_zero_a_implantacao#78]
erro ao importar modulo de teste
![image](https://user-images.githubusercontent.com/43665405/168931950-707b8825-6c1f-4390-8804-8912944e7b40.png)
usando windows
diretirio:
![image](https://user-images.githubusercontent.com/43665405/168932189-c31680e3-58b5-4022-995c-18aa6aa52d79.png)

**Comment by crijop** [comment]
No Documento falta no import o ".gerenciador".

Segue exemplo abaixo como deve ficar.

from gerenciador_tarefas.gerenciador import app, TAREFAS

**Comment by AugustoBaden** [comment]
> No Documento falta no import o ".gerenciador".
> 
> Segue exemplo abaixo como deve ficar.
> 
> from gerenciador_tarefas.gerenciador import app, TAREFAS

resolvido aqui
