### ISSUE TITLE
No teste que verifica se a tarefa tem uma descrição, esta validando o titulo

### ISSUE THREAD

**Issue by pamellasetubal** [cassiobotaro/do_zero_a_implantacao#87]
https://cassiobotaro.dev/do_zero_a_implantacao/criar/

Além de titulo, nossa tarefa deve possuir uma descrição.

def test_quando_uma_tarefa_e_submetida_deve_possuir_uma_descricao():
    cliente = TestClient(app)
    resposta = cliente.post("/tarefas", json={"titulo": "titulo"})
    assert resposta.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY

Deveria ser:

def test_quando_uma_tarefa_e_submetida_deve_possuir_uma_descricao():
    cliente = TestClient(app)
    resposta = cliente.post("/tarefas", json={"descricao": "descricao"})
    assert resposta.status_code == status.HTTP_422_UNPROCESSABLE_ENTITY

**Comment by cassiobotaro** [comment]
Após examinar atentamente, o teste está correto pois verifica que estou passando o titulo, mas falta a descrição. Uma melhoria neste teste seria a verificação do conteúdo da mensagem no erro.
