### ISSUE TITLE
Endereço errado para adicionar tarefa com httpie

### ISSUE THREAD

**Issue by uamoti** [cassiobotaro/do_zero_a_implantacao#93]
No capítulo *Criando uma tarefa*, o comando fornecido para testar criar uma tarefa foi:
`http localhost:8000 titulo="titulo" descricao="uma descrição qualquer"`
Faltou o /tarefas no endereço; deveria ser:
`http localhost:8000/tarefas titulo="titulo" descricao="uma descrição qualquer"`

**Comment by cassiobotaro** [comment]
Obrigado @uamoti !
